### ISSUE TITLE
楼主能后尝试下配合antd-mobile自定义主题

### ISSUE THREAD

**Issue by gaollard** [capslocktao/react-music-webapp#2]
我搞了好久，不是报错就是没效果。

**Comment by capslocktao** [comment]
现在的主题就是自定义的呀。antd原本是蓝色主题，现在这个是黄色。我就是照着官方文档配置的。。

**Comment by gaollard** [comment]
@capslocktao 是我自己没注意npm包版本的问题，现在已经解决了

**Comment by gaollard** [comment]
@capslocktao 有交流群们吗？不灌水，专门交流技术那种。

**Comment by capslocktao** [comment]
木有交流群，，谢谢大佬提醒我，最近正打算用ts把这个小练习重构一下呢
